export const DECK_TAGS = [
  "environment",
  "health",
  "education",
  "culture",
  "politics",
  "society",
  "business",
  "economy",
  "technology",
  "work and career",
  "finance",
  "travel and tourism",
  "media and communication",
  "global issues",
  "science",
  "food",
  "sports",
  "lifestyle",
  "relationships",
  "housing and transport",
];
